# Generated by Django 6.0.6 on 2026-06-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales', models.IntegerField()),
                ('returns', models.IntegerField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
